---
title: "Discrete Species QAQC Report"
author: "(SIDBGD) SEACAR Internal Divison for the Betterment and Goodification of Data"
date: "`r Sys.Date()`"
output: 
  pdf_document:
    extra_dependencies: ["float"]
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning=FALSE, message=FALSE)
# extrafont::loadfonts()
# extrafont::font_import()

```

# Discrete QAQC Report

This document is intended to provide an overview of newly-exported Combined Tables.  


```{r file_name_display, results='asis', eval=TRUE}
cat("The following files are included in the analysis:")
cat("  \n")
cat("  \n")

habitats <- names(data_directory)

for(h in habitats){
  new_file_name <- data_directory[["new_file_name"]][[h]]
  old_file_name <- data_directory[["old_file_name"]][[h]]
  cat(paste0("* *",new_file_name,"*  \n"))
  cat(paste0("* *",old_file_name,"*  \n"))
}

```

# Comparison of Current and Previous Exports - Overview

```{r comparison, results='asis'}
# Function to return report-ready datatable format
make_kable <- function(data_table, table_caption){
  return(
    kable(data_table,
          format="simple",
          caption=table_caption,
          booktabs=T) %>%
      kable_styling(latex_options = c("scale_down","HOLD_position"),
                    position = "center",
                    font_size = 10)
    )
}

if(habitat=="Discrete"){
  data_overview <- old_new_data
} else if(habitat %in% c("CORAL","CW","NEKTON","Oyster","SAV")){
  data_overview <- habitat_data
}

old_new_table <- data_overview %>%
  dplyr::rowwise() %>%
  dplyr::mutate(cell_color = ifelse(difference<0, "red", ifelse(difference>10000, "orange", "black"))) %>%
  dplyr::mutate(difference = cell_spec(difference, color=cell_color)) %>%
  select(-cell_color)

print(make_kable(old_new_table, "Comparison of New vs. Old data exports"))
cat("  \n")

```




```{r program_overview_table, results='asis', eval=FALSE}
cat("# Program Overview Table")
cat("  \n")

# programs_wide2 <- programs_wide %>%
#   mutate_all(funs(str_replace(., "1", "\\checkmark")))

programs_wide_kable <- kable(programs_wide,
                             format="latex",
                             caption="ProgramID Overview",
                             booktabs=T) %>%
  kable_styling(latex_options = c("scale_down","HOLD_position"),
                position = "center",
                font_size = 10)

print(programs_wide_kable)

cat("  \n")

```


```{r program_comparison, results='asis', echo=FALSE, eval=TRUE}

colorize <- function(x, color) {sprintf("\\textcolor{%s}{%s}", color, x)}

if(length(names(data_directory[['program_compare']]))>0){
  programs_differ <- TRUE
}
if(length(names(data_directory[['column_compare']]))>0){
  columns_differ <- TRUE
}
if(length(names(data_directory[['species_compare']]))>0){
  species_differ <- TRUE
}

if(programs_differ == TRUE){
  cat("\\newpage")
  cat("  \n")
  cat("# Program Differences")
  cat("  \n")
  cat(paste0(colorize("Red", "red")," ProgramIDs are Programs in the Old Exports but not in the New Exports  \n"))
  cat(paste0(colorize("Green", "green")," ProgramIDs are Programs in the New Exports but not in the Old Exports  \n"))
  cat("There is a difference in Programs between exports for the following habitats:")
  cat("    \n")
  cat("  \n")
  for(hab in names(data_directory[['program_compare']])){
    cat("  \n")
    cat(glue("## {hab}"))
    cat("  \n")
    cat(paste0("Programs in old export: (n=", length(data_directory[['program_compare']][[hab]]$old_programs),")"))
    cat("  \n")
    cat(data_directory[['program_compare']][[hab]]$old_programs, sep=", ")
    cat("  \n")
    cat(paste0("Programs in new export: (n=", length(data_directory[['program_compare']][[hab]]$new_programs),")"))
    cat("  \n")
    cat(data_directory[['program_compare']][[hab]]$new_programs, sep=", ")
    cat("  \n")
    cat("  \n")
  }
  cat("  \n")
}

if(columns_differ == TRUE){
  cat("\\newpage")
  cat("  \n")
  cat("# Column Differences")
  cat("  \n")
  cat("There is a difference in Columns between exports for the following habitats:")
  cat("  \n")
  for(hab in names(data_directory[['column_compare']])){
    cat("  \n")
    cat(glue("## {hab}"))
    cat("  \n")
    cat(paste0("**Columns in old export:** *", data_directory[["old_file_name"]][[hab]],"*"))
    cat("  \n")
    cat(data_directory[['column_compare']][[hab]][["oldColumns"]], sep=", ")
    cat("  \n")
    cat("  \n")
    cat(paste0("**Columns in new export:** *", data_directory[["new_file_name"]][[hab]],"*"))
    cat("  \n")
    cat(data_directory[['column_compare']][[hab]][["newColumns"]], sep=", ")
    cat("  \n")
  }
  cat("  \n")
}

if(species_differ == TRUE){
  cat("\\newpage")
  cat("  \n")
  cat("# Species Differences")
  cat("  \n")
  cat("There is a difference in Species between exports for the following habitats:")
  cat("  \n")
  for(hab in names(data_directory[['species_compare']])){
    cat("  \n")
    cat(glue("## {hab}"))
    cat("  \n")
    cat(paste0("**Old export:** *", data_directory[["old_file_name"]][[hab]],"*"))
    cat("  \n")
    cat(paste0("**New export:** *", data_directory[["new_file_name"]][[hab]],"*"))
    cat("  \n")
    
    table <- data_directory[["species_compare"]][[hab]][["diff_df"]] %>%
      mutate(export = cell_spec(export, color=color_code)) %>%
      select(-color_code)
    
    kable_display <- kable(table,
                           format="simple",
                           caption = "Comparison of Species",
                           booktabs=T) %>%
      kable_styling(latex_options = c("scale_down","HOLD_position"),
                    position = "center",
                    font_size = 10)
    
    print(kable_display)
    cat("  \n")
  }
  cat("  \n")
}

```


```{r detailed_comparison, results='asis', echo=FALSE, eval=FALSE}
cat("\\newpage")
cat("# Detailed Comparison")
cat("  \n")

for(p in names(data_directory)){
  cat("  \n")
  cat(glue("## {p}"))
  cat("  \n")
  print(summary(data_directory[[p]][["comparison"]]))
  cat("  \n")
}

```


```{r value_qualifiers, results='asis', eval=TRUE}
## Plotting function
plot_vq_barplot <- function(vq_source){
  if(vq_source=="STORET_WIN"){
    vq_program_table_subset <- vq_program_table[ValueQualifierSource==vq_source, ]
  } else if(vq_source=="SWMP"){
    vq_program_table_subset <- vq_program_table[ValueQualifierSource==vq_source, ]
  }
  
  plot_data <- vq_program_table_subset %>% 
    group_by(ProgramID, ValueQualifier) %>% 
    summarise(n = sum(n_vq_data),
              percentage = n / sum(vq_program_table_subset$n_vq_data)*100)
  
  plot_title <- paste0("Percentage of Value Qualified values for each program by VQ - ", vq_source)
  
  if(nrow(vq_program_table[ValueQualifierSource==vq_source])){
    return(
      print(
        ggplot(data=plot_data, aes(x=as.factor(ProgramID), y=percentage, fill=as.factor(ValueQualifier))) + 
          geom_bar(stat = "identity") +
          scale_fill_viridis(discrete = T, ) +
          labs(title = "Percentage of Value Qualified values for each program by VQ", 
               x="ProgramID", y="Percentage of total") +
          guides(fill=guide_legend(title="Value Qualifier"))
      )
    )
  }
}

if(collect_vq_data==TRUE){
  cat("\\newpage")
  cat("# Analysis of Value Qualifiers")
  cat("  \n")
  for(p in names(data_directory[["vq_table"]])){
    if(nrow(data_directory[["vq_table"]][[p]])){
      cat(glue("## {p}"))
      cat("  \n")
      vq_table <- kable(data_directory[["vq_table"]][[p]],
                        format="simple",
                        caption="Value Qualifier Overview") %>%
        kable_styling(latex_options = "scale_down",
                      position = "center",
                      font_size = 10)
      
      print(vq_table)
      cat("  \n")
      
      vq_program_table <- setDT(data_directory[["vq_program_table"]][[p]] %>% ungroup())
      vq_program_kable <- kable(vq_program_table %>%
                                  select(-ProgramName) %>%
                                  pivot_wider(names_from = ValueQualifier, values_from = n_vq_data, values_fill = 0) %>%
                                  arrange(ProgramID),
                                format="latex",
                                caption="Value Qualifier Overview by Program",
                                booktabs=T) %>%
        kable_styling(latex_options = c("scale_down","HOLD_position"),
                      position = "center")
      
      print(vq_program_kable)
      
      cat("  \n")
      cat("**STORET_WIN**  \n")
      plot_vq_barplot("STORET_WIN")
      
      cat("  \n")
      cat("**SWMP**  \n")
      plot_vq_barplot("SWMP")
      
      cat("  \n")
      cat("Problematic Programs:  \n")
      for(p_id in unique(vq_program_table$ProgramID)){
        p_name <- vq_program_table[ProgramID==p_id, unique(ProgramName)]
        cat("  \n")
        cat(paste0("* **",p_id,"** - *",p_name,"*"))
        cat("  \n")
      }
      cat("  \n")
    }
  }
}

```