---
title: "Export Comparison QAQC Report"
author: "(SIDBGD) SEACAR Internal Divison for the Betterment and Goodification of Data"
date: "`r Sys.Date()`"
output: 
  pdf_document:
    extra_dependencies: ["float"]
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning=FALSE, message=FALSE)
# extrafont::loadfonts()
# extrafont::font_import()

```


```{r functions}
# Function to return report-ready datatable format
make_kable <- function(data_table, table_caption, format="latex"){
  return(
    kbl(data_table,
        format=format,
        caption=table_caption,
        escape=F,
        digits=2,
        vline = "",
        linesep = "",
        longtable = F,
        booktabs = T) %>%
      kable_styling(latex_options = c("scale_down","HOLD_position", "striped"),
                    position = "center") %>%
      row_spec(0, italic = TRUE)
    )
}

## Plotting function for value qualifiers
plot_vq_barplot <- function(vq_source){
  if(vq_source=="STORET_WIN"){
    vq_program_table_subset <- vq_program_table[ValueQualifierSource==vq_source, ]
  } else if(vq_source=="SWMP"){
    vq_program_table_subset <- vq_program_table[ValueQualifierSource==vq_source, ]
  }
  
  plot_data <- vq_program_table_subset %>% 
    group_by(ProgramID, ValueQualifier) %>% 
    summarise(n = sum(n_vq_data),
              percentage = n / sum(vq_program_table_subset$n_vq_data)*100)
  
  plot_title <- paste0("Percentage of Value Qualified values for each program by VQ - ", vq_source)
  
  if(nrow(vq_program_table[ValueQualifierSource==vq_source])){
    return(
      print(
        ggplot(data=plot_data, aes(x=as.factor(ProgramID), y=percentage, fill=as.factor(ValueQualifier))) + 
          geom_bar(stat = "identity") +
          scale_fill_viridis(discrete = T, ) +
          labs(title = "Percentage of Value Qualified values for each program by VQ", 
               x="ProgramID", y="Percentage of total") +
          guides(fill=guide_legend(title="Value Qualifier"))
      )
    )
  }
}

```

This document is intended to provide an overview of newly exported Combined Tables.

```{r file name overview tables, results='asis', eval=TRUE}

habitats <- names(data_directory)

for(i in 1:length(habitats)){
  
  h <- habitats[i]
  
  if(!i==1){
    cat("\\newpage")
  }
  
  cat(glue("# {h}  \n"))
  cat("  \n")
  
  #######################
  ## FILE NAME DISPLAY ##
  #######################
  
  if(file_name_display==TRUE){
    cat("## Filenames")
    cat("  \n")
    cat("The following files are included in the analysis:")
    cat("  \n")
    params <- names(data_directory[[h]][["new_file_name"]])
    
    column_display <- data.table(
      "parameter" = params,
      "oldFile" = data_directory[[h]][["old_file_name"]],
      "newFile" = data_directory[[h]][["new_file_name"]])
    
    print(make_kable(column_display, paste0(h," files used in analysis")))
    cat("  \n")
  }
  
  #####################
  ## OVERVIEW TABLES ##
  #####################
  
  cat("## Overview")
  cat("  \n")
  
  comparison_table <- data_directory[[h]][["comparison_table"]]
  
  # highlight difference column for discrete/species (>10,000 values orange, negative values red)
  if(h %in% c("Discrete WQ","Species","Continuous WQ")){
    comparison_table <- comparison_table %>%
      dplyr::rowwise() %>%
      dplyr::mutate(cell_color = ifelse(difference<0, "red", "black")) %>%
      dplyr::mutate(difference = cell_spec(difference, color=cell_color)) %>%
      select(-cell_color)
  }
  
  # highlight pctChange column for continuous (>5% orange, negative values red)
  # if(h=="Continuous"){
  #   comparison_table <- comparison_table %>%
  #     dplyr::rowwise() %>%
  #     dplyr::mutate(cell_color = ifelse(pctChange<0, "red", ifelse(pctChange > 5, "orange", "black"))) %>%
  #     dplyr::mutate(pctChange = cell_spec(pctChange, color=cell_color)) %>%
  #     select(-cell_color)
  # }
  
  # Set caption
  cap <- ifelse(h=="Species",
                paste0("Comparison of New vs. Old data exports"), 
                paste0("Comparison of New vs. Old data exports - (",h,")"))
  
  print(make_kable(comparison_table, cap))
  cat("  \n")
  
  ########################
  ## PROGRAM COMPARISON ##
  ########################
  
  if(length(names(data_directory[[h]][['program_compare']]))>0){
    cat("\\newpage")
    cat("  \n")
    cat("## Program Differences")
    cat("  \n")
    cat(paste0(colorize("Red", "red")," ProgramIDs are Programs in the Old Exports but not in the New Exports  \n"))
    cat(paste0(colorize("Green", "green")," ProgramIDs are Programs in the New Exports but not in the Old Exports  \n"))
    cat("    \n")
    cat("There is a difference in Programs between exports for the following parameters:")
    cat("    \n")
    cat("  \n")
    for(par in names(data_directory[[h]][['program_compare']])){
      
      old_programs <- data_directory[[h]][['program_compare']][[par]]$old_programs
      new_programs <- data_directory[[h]][['program_compare']][[par]]$new_programs
      
      cat("  \n")
      cat(glue("### {par}"))
      cat("  \n")
      cat(paste0("Programs in old export: (n=", length(old_programs),")"))
      cat("  \n")
      cat(old_programs, sep=", ")
      cat("  \n")
      cat(paste0("Programs in new export: (n=", length(new_programs),")"))
      cat("  \n")
      cat(new_programs, sep=", ")
      cat("  \n")
      cat("  \n")
      cat("  \n")
    }
    cat("  \n")
  }
  
  ####################
  ## PROGRAM COUNTS ##
  ####################
  
  if(nrow(data_directory[[h]][["program_count_table"]])>0){
    
    cat("\\newpage")
    cat("  \n")
    cat("## Differences in Program data between exports")
    cat("  \n")
    
    program_count_table <- data_directory[[h]][["program_count_table"]] %>%
      rowwise() %>%
      mutate(cell_color = ifelse(difference<0, "red", "black")) %>%
      mutate(difference = cell_spec(difference, color=cell_color)) %>%
      select(-cell_color)
    
    names(program_count_table) <- gsub("_", " ", names(program_count_table))
    
    # remove duplicate entries
    program_count_table <- distinct(program_count_table)
    
    if(h=="Species"){
      for(hab in unique(program_count_table$habitat)){
        program_count_table_hab <- program_count_table %>% filter(habitat==hab)
        cat("  \n")
        cat(glue("### {hab}"))
        cat("  \n")
        
        for(p in unique(program_count_table_hab$ParameterName)){
          print(make_kable(
            program_count_table_hab %>% filter(ParameterName==p) %>% 
              select(-habitat) %>%
              arrange(ProgramID),
            paste0("Number of data entries by program -\n", p)))
        }
      }
    } else {
      for(p in unique(program_count_table$parameter)){
        cat("  \n")
        cat(glue("### {p}"))
        cat("  \n")
        print(make_kable(
          program_count_table %>% filter(parameter==p) %>% 
            select(-parameter) %>%
            arrange(ProgramID),
          paste0("Number of data entries by program -\n", p)))
      }      
    }
  }
  
  #######################
  ## COLUMN COMPARISON ##
  #######################
  
  if(show_columns){
    if(length(names(data_directory[[h]][['column_compare']]))>0){
      cat("\\newpage")
      cat("  \n")
      cat("## Column Differences")
      cat("  \n")
      cat("There is a difference in Columns between exports for the following parameters:")
      cat("  \n")
      for(par in names(data_directory[[h]][['column_compare']])){
        cat("  \n")
        cat(glue("### {par}"))
        cat("  \n")
        cat("Columns in old export: ")
        cat("  \n")
        print(make_kable(data_directory[[h]][['column_compare']][[par]][["oldColumns"]], "Old Columns", format = "simple"))
        cat("  \n")
        cat("Columns in new export: ")
        cat("  \n")
        print(make_kable(data_directory[[h]][['column_compare']][[par]][["newColumns"]], "New Columns", format = "simple"))
        cat("  \n")
      }
      cat("  \n")
    }
  }
  
  ##################################
  ## SEACAR_QAQCFlagCode Overview ##
  ##################################
  
  if(show_flag_overview==TRUE){
    if(length(names(data_directory[[h]][["flag_overview_wide"]]))>0){
    
    cat("\\newpage")
    cat("  \n")
    cat("## Overview of SEACAR flag codes")
    cat("  \n")
    
    for(par in names(data_directory[[h]][["flag_overview_wide"]])){
      wide_table <- data_directory[[h]][["flag_overview_wide"]][[par]]
      
      if(h=="Species"){wide_table <- wide_table %>% arrange(ProgramID, ParameterName)}
      
      names(wide_table) <- gsub("_", " ", names(wide_table))
      
      # Only print table when there are results
      if(nrow(wide_table)>0){
        cat("  \n")
        cat(glue("### {par}"))
        cat("  \n")
        
        print(make_kable(wide_table, paste0("Overview of SEACAR Flag Codes for ",par), format="latex"))
        cat("  \n")
      }
      
      cat("  \n")
    }
  }
  }
  
  ######################
  ## VALUE QUALIFIERS ##
  ######################
  
  if(h=="Discrete" & collect_vq_data==TRUE){
    cat("\\newpage")
    cat("## Analysis of Value Qualifiers")
    cat("  \n")
    
    for(p in names(data_directory[[h]][["vq_table"]])){
      if(nrow(data_directory[[h]][["vq_table"]][[p]])){
        cat(glue("### {p}"))
        cat("  \n")
        vq_table <- kable(data_directory[[h]][["vq_table"]][[p]],
                          format="simple",
                          caption="Value Qualifier Overview") %>%
          kable_styling(latex_options = "scale_down",
                        position = "center",
                        font_size = 10)
        
        print(vq_table)
        cat("  \n")
        
        vq_program_table <- setDT(data_directory[[h]][["vq_program_table"]][[p]] %>% ungroup())
        vq_program_kable <- kable(vq_program_table %>%
                                    select(-ProgramName) %>%
                                    pivot_wider(names_from = ValueQualifier, values_from = n_vq_data, values_fill = 0) %>%
                                    arrange(ProgramID),
                                  format="latex",
                                  caption="Value Qualifier Overview by Program",
                                  booktabs=T) %>%
          kable_styling(latex_options = c("scale_down","HOLD_position"),
                        position = "center")
        
        print(vq_program_kable)
        
        cat("  \n")
        cat("**STORET_WIN**  \n")
        plot_vq_barplot("STORET_WIN")
        
        cat("  \n")
        cat("**SWMP**  \n")
        plot_vq_barplot("SWMP")
        
        cat("  \n")
        cat("Problematic Programs:  \n")
        
        for(p_id in unique(vq_program_table$ProgramID)){
          p_name <- vq_program_table[ProgramID==p_id, unique(ProgramName)]
          cat("  \n")
          cat(paste0("* **",p_id,"** - *",p_name,"*"))
          cat("  \n")
        }
        
        cat("  \n")
      }
    }
  }
  
  #####################
  ### Jan 1st Dates ###
  #####################
  
  if(h %in% c("Species", "Discrete WQ")){
    # Filter out empty data frames and then combine them
    non_empty_dfs <- Filter(function(df) nrow(df) > 0, data_directory[[h]][["jan_dates"]])
    jan_dates <- bind_rows(non_empty_dfs)
    
    if(h=="Species"){
      jan_dates_display <- jan_dates %>% 
        group_by(Habitat, ProgramID, ParameterName) %>% 
        reframe(n = n(),years = paste(sort(unique(Year)), collapse = ", "))
    } else if(h=="Discrete WQ"){
      jan_dates_display <- jan_dates %>% 
        group_by(ProgramID, ParameterName) %>% 
        reframe(n = n(),years = paste(sort(unique(Year)), collapse = ", "))
    }
    
    cat("  \n")
    cat("\\newpage")
    cat("## January 1st Dates")
    cat("  \n")
    cat("Database defaults to January 1st dates when SampleDate is unavailable or incorrectly collected from raw data. 
        A SampleDate of January 1st is not necessarily an error, but a large number of January 1st dates should be examined further. 
        Continuous WQ is excluded from this analysis.")
    cat("  \n")
    print(
      make_kable(
        jan_dates_display, 
        table_caption = "Summary of January 1st Dates", 
        format = "latex"
      )
    )
    cat("  \n")
    
  }
  
}

```


```{r qaqc flag check, results='asis'}

check_flag <- function(h, qtype="quantile"){
  data_combined_subset <- data.table()
  
  if(qtype=="quantile"){
    high_flag_code <- "17Q"
    low_flag_code <- "16Q"
  } else if(qtype=="threshold"){
    high_flag_code <- "2Q"
    low_flag_code <- "4Q"
  }
  # Account for exact matches
  high_flag_code <- paste0("\\b", high_flag_code, "\\b")
  low_flag_code <- paste0("\\b", low_flag_code, "\\b")
  
  if(!h=="Species"){
    for(i in names(data_directory[[h]][[qtype]])){
      data_combined_subset <- rbind(data_combined_subset, plyr::rbind.fill(data_directory[[h]][[qtype]][[i]]), fill=TRUE)
    }
    
    # Compute statistics grouped by ParameterName
    flag_table <- data_combined_subset[,
                                       .(n_high = sum(q_subset == "high"),
                                         n_high_flagged = sum(str_detect(SEACAR_QAQCFlagCode, high_flag_code)),
                                         n_low = sum(q_subset == "low"),
                                         n_low_flagged = sum(str_detect(SEACAR_QAQCFlagCode, low_flag_code)),
                                         n_included = sum(Include==1)),
                                       by = ParameterName]
    
  } else {
    for(type in names(data_directory[[h]][[qtype]])){
      for(i in names(data_directory[[h]][[qtype]][[type]])){
        data2 <- plyr::rbind.fill(data_directory[[h]][[qtype]][[type]][[i]])
        data2$habitat <- type
        
        data_combined_subset <- rbind(data_combined_subset, data2, fill=TRUE)
      }
    }
    
    # Compute statistics grouped by ParameterName
    flag_table <- data_combined_subset[, 
                                       .(n_high = sum(q_subset == "high"),
                                         n_high_flagged = sum(str_detect(SEACAR_QAQCFlagCode, high_flag_code)),
                                         n_low = sum(q_subset == "low"),
                                         n_low_flagged = sum(str_detect(SEACAR_QAQCFlagCode, low_flag_code))), 
                                       by = list(ParameterName, habitat)]
  }
  
  # add signifier to any entry that doesn't have correct flag
  # Color coding cells
  flag_table <- flag_table %>%
    dplyr::rowwise() %>%
    dplyr::mutate(cell_color_low = ifelse(n_low == n_low_flagged, "black", "red"),
                  cell_color_high = ifelse(n_high == n_high_flagged, "black", "red")) %>%
    dplyr::mutate(n_low = cell_spec(n_low, color = cell_color_low),
                  n_low_flagged = cell_spec(n_low_flagged, color = cell_color_low),
                  n_high = cell_spec(n_high, color = cell_color_high),
                  n_high_flagged = cell_spec(n_high_flagged, color = cell_color_high)) %>%
    select(-c(cell_color_high, cell_color_low))
  
  # Provide "Include" column for threshold tables only
  if(!qtype=="threshold" & !h=="Species"){flag_table <- flag_table %>% select(-n_included)}
  
  names(flag_table) <- gsub("_", " ", names(flag_table))
  
  flag_display_table <- kable(flag_table,
                              format="latex",
                              digits = 2,
                              escape = F,
                              booktabs=T) %>%
    kable_styling(latex_options=c("scale_down", "HOLD_position"),
                  position = "center")
  
  unflagged_display <- data_combined_subset[
    (q_subset=="high" & !str_detect(SEACAR_QAQCFlagCode, "17Q")) | 
      (q_subset=="low" & !str_detect(SEACAR_QAQCFlagCode, "16Q")),
    c("RowID","ProgramID","ParameterName","ResultValue","SEACAR_QAQCFlagCode",
      "SEACAR_QAQC_Description","q_subset")]
  
  if(nrow(flag_table)>0){
    print(flag_display_table)
  } else {
    cat("  \n")
    cat(glue("No {qtype} values detected"))
    cat("  \n")
  }
  
  if(nrow(unflagged_display)>0){
    
    names(unflagged_display) <- gsub("_", " ", names(unflagged_display))
    
    unflag_display_table <- make_kable(unflagged_display %>% 
                                         select(-"SEACAR QAQC Description") %>%
                                         arrange(ProgramID),
                                       table_caption = "SEACAR QAQC Flag Code discrepancies",
                                       format = "latex")
    if(h=="Species"){
      cat("  \n")
      cat("Entries where ResultValue is above or below quantile, but expected SEACAR_QAQCFlagCode is not being applied")
      cat("  \n")
      print(unflag_display_table)
    }
    
    cat("  \n")
    
  }
  
}

for(i in 1:length(habitats)){
  
  h <- habitats[i]
  
  if(!i==1){
    cat("\\newpage")
  } else {
    cat("# QAQC Flag Check")
    cat("  \n")
    cat(paste0("* n_high is the amount of data above the quantile value.   \n * n_high_flagged is the amount of data above the quantile value AND containing proper SEACARQAQCFlag of 17Q (ResultValue above quantile value)."))
    cat("  \n")
    cat(paste0("* n_low is the amount of data below the quantile value.   \n * n_low_flagged is the amount of data below the quantile value AND containing proper SEACARQAQCFlag of 16Q (ResultValue below quantile value)."))
    cat("  \n")
    cat("* If everything is in order, these values should be the same. Any discrepancies therein should be fastidiously noted.")
    cat("  \n")
    cat("* Flagcodes for **Threshold** checks: *2Q* & *4Q*")
    cat("  \n")
    cat(paste0("* Quantiles and Threshold checks have been compared with *", db_threshold_file, "*"))
    cat("  \n")
  }
  
  cat("  \n")
  cat(glue("## {h}"))
  cat("  \n")
  
  cat(glue("### Quantile Check"))
  cat("  \n")
  
  cat("  \n")
  check_flag(h, qtype="quantile")
  cat("  \n")
  
  cat(glue("### Threshold Check"))
  cat("  \n")
  check_flag(h, qtype="threshold")
  cat("  \n")
  
}

```

```{r expected values check, results='asis'}
# Function to check values
expectedCheck <- function(param, habitat, df, pid, return="n"){
  setDT(df)
  df <- df[ParameterName==param & ProgramID==pid, ]
  # Grab text-based value from DB Thresholds file
  expected_text <- db_thresholds[ParameterName==param & Habitat==habitat, 
                                 ExpectedValues]
  # Only apply expected values check where necessary
  if(length(expected_text)>0){
    
    if(param=="Percent Occurrence" & habitat=="Submerged Aquatic Vegetation"){
      expected_text <- "0 to 100 (inclusive)"
    }
    
    if(expected_text=="0 to 100 (inclusive)"){
      e_data <- df[Include==1 & ParameterName==param &
                     (ResultValue < 0 & ResultValue > 100), ]
    }
    if(expected_text=="boolean"){
      e_data <- df[Include==1 & ParameterName==param &
                     (!ResultValue %in% c(0,1)), ]
    }
    if(expected_text=="0 or positive integers"){
      e_data <- df[Include==1 & ParameterName==param &
                     (!ResultValue >= 0), ]
    }
    if(expected_text=="0,0.1,0.5,1,2,3,4,5"){
      e_data <- df[Include==1 & ParameterName==param &
                     (!ResultValue %in% c(0,0.1,0.5,1,2,3,4,5)), ]
    }
    if(expected_text=="VOB, 999, >B"){
      # Handled in other function
      next
    }
  }
  if(return=="n"){
    return(nrow(e_data))
  } else if(return=="text"){
    return(expected_text)
  }
}

# Gather 15Q values
expected_vals <- data.table()
for(i in names(data_directory)){
  for(p in names(data_directory[[i]][["fifteenQ"]])){
    df <- data_directory[[i]][["fifteenQ"]][[p]]
    if(nrow(df)>0){
      expected_vals <- rbind(expected_vals, df)
    }
  }  
}

expected_values <- expected_vals %>% 
  group_by(Habitat, ParameterName, ProgramID) %>%
  summarise("N Data Flagged" = n())

expected_values <- expected_values %>%
  rowwise() %>%
  mutate("N Unexpected Values" = expectedCheck(ParameterName, Habitat, 
                                                       expected_vals, ProgramID, 
                                                       return="n"),
         "Expected Values" = expectedCheck(ParameterName, Habitat, 
                                           expected_vals, ProgramID, 
                                           return="text"))

cat("  \n")
cat("\\newpage")
cat("# Expected Values Check (15Q)")
cat("  \n")
for(habitat in unique(expected_values$Habitat)){
  cat(glue("## {habitat}"))
  cat("  \n")
  print(make_kable(expected_values %>%
                     ungroup() %>%
                     select(-Habitat), 
                   table_caption = "Overview of 15Q - Expected Values Check"))
  cat("  \n")
}
cat("  \n")

```

```{r Secchi VOB, results='asis', eval=FALSE}
secchiCheck <- function(pid, df){
  e_data <- df %>% filter(ProgramID==pid, str_detect(SEACAR))
  return(nrow(e_data))
}

secchi <- fread(secchi <- str_subset(wq_disc_files, "Secchi"), 
                sep='|', na.strings = "NULL")

secchi_vob <- secchi %>% filter(TotalDepth_m==ResultValue)

secchi_display <- secchi_vob %>% group_by(ProgramID) %>%
  summarise("N Secchi VOB" = n())
  
secchi_display <- secchi_display %>%
  rowwise() %>%
  mutate("N Flagged 8Q" = secchiCheck(ProgramID, secchi_vob))

cat("  \n")
cat("# Secchi Depth Visible on Bottom")
cat("  \n")
cat("*N Secchi VOB* is the count of data where TotalDepth_m == ResultValue")
cat("  \n")
cat("*N Flagged 8Q* is the count of data whereSEACAR_QAQCFlagCode contains *8Q* designation")
cat("  \n")
print(make_kable(secchi_display, 
                 table_caption = "Overview of 8Q - Secchi Depth: Visible on Bottom"))
cat("  \n")

```
